spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:goldenstay_db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${PGUSER:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${PGPASSWORD:}}
spring.jpa.hibernate.ddl-auto=update
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:4200}
